name: CI

on:
  pull_request: {}
  push: { branches: [ master ] }

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "default" }
          - { name: "over TCP", dockerHost: "tcp://127.0.0.1:2375" }
          - { name: "Docker 18.06.3", dockerVersion: "18.06.3~ce~3-0~ubuntu" }

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Configure Docker
        env:
          DOCKER_VERSION: ${{matrix.dockerVersion}}
          DOCKER_HOST: ${{matrix.dockerHost}}
        run: .ci/setup_docker.sh
      - name: Build with Maven
        env:
          DOCKER_HOST: ${{matrix.dockerHost}}
        run: ./mvnw --no-transfer-progress verify
      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: lodr9d83
          CIMATE_CI_KEY: "CI / ${{matrix.name}}"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate "**/TEST-*.xml"
