name: CI

on:
  pull_request: {}
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "default", javaVersion: 8 }
          - { name: "default", javaVersion: 17 }
          - { name: "default", javaVersion: 21 }
          - { name: "Docker 19.03.9", dockerVersion: "v19.03.9", javaVersion: 8 }
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: temurin
      - name: Configure Docker
        id: setup_docker
        uses: docker/setup-docker-action@v4
        with:
          version: ${{matrix.dockerVersion}}
          channel: stable
      - name: Build with Maven
        env:
          DOCKER_HOST: ${{steps.setup_docker.outputs.sock}}
        run: ./mvnw --no-transfer-progress verify

  tcp:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - name: Configure Docker
        id: setup_docker
        uses: crazy-max/docker-setup-docker-action@expose-tcp-input
        with:
          channel: stable
          tcp-port: 2375
      - name: Build with Maven
        env:
          DOCKER_HOST: ${{steps.setup_docker.outputs.tcp}}
        run: ./mvnw --no-transfer-progress verify
